<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-1SGJJN07" ignored="0" name="Activity1" tests="2" failures="1" timestamp="22 Jul 2018 15:22:20 GMT" time="23.268" errors="0">
  <testcase name="doMerge" time="5.359" classname="testng.MergeLeadFrameWork">
    <failure type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at week2.day2.wdmethods.SeMethods.switchToWindow(SeMethods.java:321)
at testng.MergeLeadFrameWork.doMerge(MergeLeadFrameWork.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- doMerge -->
  <testcase name="createLead" time="8.582" classname="testng.CreateLeadFrameWork"/>
</testsuite> <!-- Activity1 -->
